# Generated by Django 2.1 on 2019-01-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='content',
        ),
    ]
